### ISSUE TITLE
Перемещение предметов кликом под пуллом

### ISSUE THREAD

**Issue by Hellrole** [animusdev/liberty-green#36]
**С Л О М А Н О**
https://i.gyazo.com/293dd30f6e570f7d700a382e812fb25f.mp4

**Comment by ucnaHez** [comment]
У меня оно наоборот слишком хорошо работает - когда клик предметом, тоже перемещается. Бесит.

**Comment by ucnaHez** [comment]
А со структурами не работает вообще - хотя с ними это как раз жизненно важная функция против застревания в техах с тележкой уборщика

**Comment by ucnaHez** [comment]
что происходит
когда пофиксить успели
